# -*- coding: utf-8 -*-
"""Sent_Analysis_Hybrid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkkJo23m1qFR-tvziqiIkwyJsP7MOEhb
"""

import os
import random
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report

from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import XGBClassifier

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)

base_path = "/content/drive/MyDrive/data/data/non_cuda"

datasets_local = {
    "airline": pd.read_csv(os.path.join(base_path, "airline.tsv"), sep="\t", encoding="latin1"),
    "eco_news": pd.read_csv(os.path.join(base_path, "eco_news.tsv"), sep="\t", encoding="latin1"),
    "glo_warm": pd.read_csv(os.path.join(base_path, "glo_warm.tsv"), sep="\t", encoding="latin1"),
    "text_emo": pd.read_csv(os.path.join(base_path, "text_emo.tsv"), sep="\t", encoding="latin1"),
}

for name, df in datasets_local.items():
    print("====", name, "====")
    print(df.shape)
    print(df.head(2))
    print(df["label"].value_counts().head(), "\n")

from collections import defaultdict

encoders = {}
splits = {}

def prepare_local_dataset(name, test_size=0.15, val_size=0.15):
    df = datasets_local[name].copy()
    df["text"] = df["text"].astype(str)
    df["label"] = df["label"].astype(str).str.strip().str.lower()

    le = LabelEncoder()
    df["label_id"] = le.fit_transform(df["label"])
    encoders[name] = le

    X_train, X_temp, y_train, y_temp = train_test_split(
        df["text"], df["label_id"], test_size=(test_size + val_size), random_state=42, stratify=df["label_id"]
    )
    rel_val = val_size / (test_size + val_size)
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=(1 - rel_val), random_state=42, stratify=y_temp
    )

    splits[name] = {
        "train": (X_train, y_train),
        "val": (X_val, y_val),
        "test": (X_test, y_test),
    }
    print(f"{name}: classes -> {list(le.classes_)}")
    for k, (X, y) in splits[name].items():
        print(f"  {k}: {len(X)} examples")
    return splits[name]

_ = prepare_local_dataset("airline")
_ = prepare_local_dataset("eco_news")
_ = prepare_local_dataset("glo_warm")
_ = prepare_local_dataset("text_emo")

from datasets import load_dataset

hf_datasets = {}

hf_datasets["imdb"] = load_dataset("imdb")                     # binary
hf_datasets["yelp_polarity"] = load_dataset("yelp_polarity")   # binary
hf_datasets["amazon_polarity"] = load_dataset("amazon_polarity")  # binary
hf_datasets["tweet_eval_sentiment"] = load_dataset("tweet_eval", "sentiment")  # 3-way

for name, ds in hf_datasets.items():
    print("====", name, "====")
    print(ds)
    print(ds["train"][0])
    print()

def prepare_hf_dataset_for_classification(name, text_col="text", label_col="label", sample_train=None, sample_test=None):
    ds = hf_datasets[name]
    train_ds = ds["train"]
    test_ds = ds["test"] if "test" in ds else ds["validation"]

    if sample_train is not None:
        train_ds = train_ds.shuffle(seed=42).select(range(sample_train))
    if sample_test is not None:
        test_ds = test_ds.shuffle(seed=42).select(range(sample_test))

    train_df = pd.DataFrame({ "text": train_ds[text_col], "label_id": train_ds[label_col] })
    test_df = pd.DataFrame({ "text": test_ds[text_col], "label_id": test_ds[label_col] })

    le = LabelEncoder()
    le.fit(train_df["label_id"].tolist() + test_df["label_id"].tolist())

    train_df["label_id"] = le.transform(train_df["label_id"])
    test_df["label_id"] = le.transform(test_df["label_id"])

    X_train, X_val, y_train, y_val = train_test_split(
        train_df["text"], train_df["label_id"], test_size=0.15, random_state=42, stratify=train_df["label_id"]
    )

    splits[name] = {
        "train": (X_train, y_train),
        "val": (X_val, y_val),
        "test": (test_df["text"], test_df["label_id"]),
    }
    encoders[name] = le

    print(f"{name}: classes -> {list(le.classes_)}")
    for k, (X, y) in splits[name].items():
        print(f"  {k}: {len(X)} examples")
    return splits[name]

_ = prepare_hf_dataset_for_classification("imdb", sample_train=8000, sample_test=2000)

def run_xgboost_experiment(dataset_name, max_features=50000, n_estimators=300):
    X_train, y_train = splits[dataset_name]["train"]
    X_val, y_val = splits[dataset_name]["val"]
    X_test, y_test = splits[dataset_name]["test"]

    tfidf = TfidfVectorizer(
        max_features=max_features,
        ngram_range=(1, 2),
        lowercase=True,
        strip_accents="unicode",
    )
    X_train_vec = tfidf.fit_transform(X_train)
    X_val_vec = tfidf.transform(X_val)
    X_test_vec = tfidf.transform(X_test)

    num_classes = len(np.unique(y_train))
    xgb = XGBClassifier(
        n_estimators=n_estimators,
        max_depth=8,
        learning_rate=0.1,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="multi:softprob" if num_classes > 2 else "binary:logistic",
        eval_metric="mlogloss",
        tree_method="hist",  # change to "gpu_hist" if your XGBoost build supports GPU
        n_jobs=-1,
    )

    xgb.fit(X_train_vec, y_train, eval_set=[(X_val_vec, y_val)], verbose=True)

    def evaluate(split_name, X_vec, y_true):
        y_pred = xgb.predict(X_vec)
        acc = accuracy_score(y_true, y_pred)
        f1_macro = f1_score(y_true, y_pred, average="macro")
        print(f"{split_name} accuracy: {acc:.4f}, macro-F1: {f1_macro:.4f}")
        return y_pred

    print("=== XGBoost results on", dataset_name, "===")
    _ = evaluate("Val", X_val_vec, y_val)
    y_pred_test = evaluate("Test", X_test_vec, y_test)
    print("\nClassification report (test):")
    print(classification_report(y_test, y_pred_test, digits=4))

# examples:
run_xgboost_experiment("airline")
# run_xgboost_experiment("text_emo")
# run_xgboost_experiment("imdb")

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup,
)

from torch.optim import AdamW

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

def create_dataloaders(dataset_name, max_length=128, batch_size=64):
    X_train, y_train = splits[dataset_name]["train"]
    X_val, y_val = splits[dataset_name]["val"]
    X_test, y_test = splits[dataset_name]["test"]

    def encode_texts(texts):
        return tokenizer(
            list(texts),
            padding="max_length",
            truncation=True,
            max_length=max_length,
            return_tensors="pt",
        )

    train_enc = encode_texts(X_train)
    val_enc = encode_texts(X_val)
    test_enc = encode_texts(X_test)

    train_dataset = TextDataset(train_enc, y_train.to_numpy())
    val_dataset = TextDataset(val_enc, y_val.to_numpy())
    test_dataset = TextDataset(test_enc, y_test.to_numpy())

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    num_labels = len(np.unique(y_train))
    return train_loader, val_loader, test_loader, num_labels

train_loader_airline, val_loader_airline, test_loader_airline, num_labels_airline = create_dataloaders("airline")
num_labels_airline

def compute_metrics_from_logits(all_logits, all_labels):
    preds = np.argmax(all_logits, axis=1)
    acc = accuracy_score(all_labels, preds)
    f1 = f1_score(all_labels, preds, average="macro")
    return acc, f1

def evaluate_model(model, data_loader):
    model.eval()
    all_logits = []
    all_labels = []
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch["input_ids"].to(device)
            labels = batch["labels"].to(device)
            logits = model(input_ids=input_ids)  # RNN models ignore attention mask
            all_logits.append(logits.detach().cpu().numpy())
            all_labels.append(labels.detach().cpu().numpy())
    all_logits = np.concatenate(all_logits, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    acc, f1 = compute_metrics_from_logits(all_logits, all_labels)
    return acc, f1

def train_rnn_style_model(model, train_loader, val_loader, num_epochs=4, lr=1e-3):
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(1, num_epochs + 1):
        model.train()
        total_loss = 0.0
        for batch in train_loader:
            input_ids = batch["input_ids"].to(device)
            labels = batch["labels"].to(device)

            optimizer.zero_grad()
            logits = model(input_ids=input_ids)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        val_acc, val_f1 = evaluate_model(model, val_loader)
        print(f"Epoch {epoch}: train_loss={total_loss/len(train_loader):.4f}, val_acc={val_acc:.4f}, val_f1={val_f1:.4f}")
    return model

def evaluate_transformer(model, data_loader):
    model.eval()
    all_logits = []
    all_labels = []
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            all_logits.append(logits.detach().cpu().numpy())
            all_labels.append(labels.detach().cpu().numpy())
    all_logits = np.concatenate(all_logits, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    acc, f1 = compute_metrics_from_logits(all_logits, all_labels)
    return acc, f1

def train_transformer_experiment(
    dataset_name,
    model_name="distilbert-base-uncased",
    epochs=3,
    max_length=128,
    batch_size=32,
    lr=2e-5,
):
    train_loader, val_loader, test_loader, num_labels = create_dataloaders(
        dataset_name, max_length=max_length, batch_size=batch_size
    )

    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
    )
    model.to(device)

    optimizer = AdamW(model.parameters(), lr=lr)
    total_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps,
    )

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        for batch in train_loader:
            optimizer.zero_grad()
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            loss.backward()
            optimizer.step()
            scheduler.step()
            total_loss += loss.item()

        val_acc, val_f1 = evaluate_transformer(model, val_loader)
        print(f"Epoch {epoch}: train_loss={total_loss/len(train_loader):.4f}, val_acc={val_acc:.4f}, val_f1={val_f1:.4f}")

    test_acc, test_f1 = evaluate_transformer(model, test_loader)
    print(f"\nTest results (Transformer {model_name}, {dataset_name}): acc={test_acc:.4f}, macro_f1={test_f1:.4f}")
    return model

transformer_airline = train_transformer_experiment("airline", epochs=5)

from datasets import load_dataset

# Add Twitter emotion dataset (6 emotions: anger, fear, joy, love, sadness, surprise)
hf_datasets["emotion"] = load_dataset("dair-ai/emotion")

# Prepare both 'emotion' and tweet_eval_sentiment in the same way as imdb
_ = prepare_hf_dataset_for_classification("emotion", text_col="text", label_col="label")
_ = prepare_hf_dataset_for_classification("tweet_eval_sentiment", text_col="text", label_col="label")

print("Available datasets in splits:")
print(list(splits.keys()))

exp_results = []

def add_result(dataset, model_name, val_acc, val_f1, test_acc, test_f1):
    exp_results.append({
        "dataset": dataset,
        "model": model_name,
        "val_accuracy": val_acc,
        "val_macro_f1": val_f1,
        "test_accuracy": test_acc,
        "test_macro_f1": test_f1,
    })

def run_xgboost_experiment_metrics(dataset_name, max_features=50000, n_estimators=300):
    X_train, y_train = splits[dataset_name]["train"]
    X_val, y_val = splits[dataset_name]["val"]
    X_test, y_test = splits[dataset_name]["test"]

    tfidf = TfidfVectorizer(
        max_features=max_features,
        ngram_range=(1, 2),
        lowercase=True,
        strip_accents="unicode",
    )
    X_train_vec = tfidf.fit_transform(X_train)
    X_val_vec = tfidf.transform(X_val)
    X_test_vec = tfidf.transform(X_test)

    num_classes = len(np.unique(y_train))
    xgb = XGBClassifier(
        n_estimators=n_estimators,
        max_depth=8,
        learning_rate=0.1,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="multi:softprob" if num_classes > 2 else "binary:logistic",
        eval_metric="mlogloss",
        tree_method="hist",  # change to "gpu_hist" if your build supports it
        n_jobs=-1,
    )

    xgb.fit(X_train_vec, y_train, eval_set=[(X_val_vec, y_val)], verbose=True)

    def eval_block(X_vec, y_true):
        y_pred = xgb.predict(X_vec)
        acc = accuracy_score(y_true, y_pred)
        f1 = f1_score(y_true, y_pred, average="macro")
        return acc, f1

    val_acc, val_f1 = eval_block(X_val_vec, y_val)
    test_acc, test_f1 = eval_block(X_test_vec, y_test)

    print(f"[XGBoost] {dataset_name} -> val_acc={val_acc:.4f}, val_f1={val_f1:.4f}, test_acc={test_acc:.4f}, test_f1={test_f1:.4f}")
    return val_acc, val_f1, test_acc, test_f1

def run_rnn_with_metrics(dataset_name, model_type="lstm", epochs=5,
                         max_length=128, batch_size=64, embed_dim=128, hidden_dim=128):
    train_loader, val_loader, test_loader, num_labels = create_dataloaders(
        dataset_name, max_length=max_length, batch_size=batch_size
    )
    vocab_size = tokenizer.vocab_size

    if model_type == "rnn":
        model = RNNClassifier(vocab_size, embed_dim, hidden_dim, num_labels)
    elif model_type == "lstm":
        model = LSTMClassifier(vocab_size, embed_dim, hidden_dim, num_labels)
    elif model_type == "gru":
        model = GRUClassifier(vocab_size, embed_dim, hidden_dim, num_labels)
    elif model_type == "bilstm_rnn":
        model = BiLSTM_RNN_Classifier(vocab_size, embed_dim, hidden_dim, hidden_dim, num_labels)
    elif model_type == "bilstm_gru":
        model = BiLSTM_GRU_Classifier(vocab_size, embed_dim, hidden_dim, hidden_dim, num_labels)
    else:
        raise ValueError("Unknown model_type")

    print(f"\n[{model_type.upper()}] Training on {dataset_name}")
    model = train_rnn_style_model(model, train_loader, val_loader, num_epochs=epochs, lr=1e-3)

    val_acc, val_f1 = evaluate_model(model, val_loader)
    test_acc, test_f1 = evaluate_model(model, test_loader)
    print(f"[{model_type.upper()}] {dataset_name} -> val_acc={val_acc:.4f}, val_f1={val_f1:.4f}, test_acc={test_acc:.4f}, test_f1={test_f1:.4f}")
    return val_acc, val_f1, test_acc, test_f1

def run_transformer_with_metrics(
    dataset_name,
    model_name="distilbert-base-uncased",
    epochs=2,
    max_length=128,
    batch_size=32,
    lr=2e-5,
):
    train_loader, val_loader, test_loader, num_labels = create_dataloaders(
        dataset_name, max_length=max_length, batch_size=batch_size
    )

    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
    )
    model.to(device)

    optimizer = AdamW(model.parameters(), lr=lr)
    total_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps,
    )

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        for batch in train_loader:
            optimizer.zero_grad()
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            loss.backward()
            optimizer.step()
            scheduler.step()
            total_loss += loss.item()

        val_acc, val_f1 = evaluate_transformer(model, val_loader)
        print(f"[TRANSF {model_name}] {dataset_name}, epoch {epoch}: train_loss={total_loss/len(train_loader):.4f}, val_acc={val_acc:.4f}, val_f1={val_f1:.4f}")

    val_acc, val_f1 = evaluate_transformer(model, val_loader)
    test_acc, test_f1 = evaluate_transformer(model, test_loader)
    print(f"[TRANSF {model_name}] {dataset_name} -> val_acc={val_acc:.4f}, val_f1={val_f1:.4f}, test_acc={test_acc:.4f}, test_f1={test_f1:.4f}")
    return val_acc, val_f1, test_acc, test_f1

# 1) Build combined dataset from your uploaded TSVs + Hugging Face emotion datasets
import pandas as pd
import numpy as np
from datasets import load_dataset

local_paths = {
    "airline": "/content/drive/MyDrive/data/data/non_cuda/airline.tsv",
    "eco_news": "/content/drive/MyDrive/data/data/non_cuda/eco_news.tsv",
    "glo_warm": "/content/drive/MyDrive/data/data/non_cuda/glo_warm.tsv",
    "text_emo": "/content/drive/MyDrive/data/data/non_cuda/text_emo.tsv",
}

parts = []
for name, path in local_paths.items():
    df = pd.read_csv(path, sep="\t", encoding="latin1")
    df = df.rename(columns={c: c.strip() for c in df.columns})
    if "text" not in df.columns or "label" not in df.columns:
        raise ValueError(f"{path} must contain 'text' and 'label' columns. Found: {df.columns.tolist()}")
    tmp = df[["text","label"]].copy()
    tmp["source"] = name
    parts.append(tmp)

hf_emotion = load_dataset("dair-ai/emotion")   # multi-emotion tweets
hf_tweet_eval = load_dataset("tweet_eval", "sentiment")  # 3-class sentiment

def hf_to_df(ds, text_col="text", label_col="label", source_name="hf"):
    rows = []
    for split in ds.keys():
        for ex in ds[split]:
            rows.append({"text": ex[text_col], "label": str(ex[label_col]), "source": source_name})
    return pd.DataFrame(rows)

parts.append(hf_to_df(hf_emotion, source_name="emotion_hf"))
parts.append(hf_to_df(hf_tweet_eval, source_name="tweet_eval"))

combined_df = pd.concat(parts, ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
print("Combined shape:", combined_df.shape)
print(combined_df.source.value_counts())

# 2) Normalize labels, encode, and create stratified train/val/test splits
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

combined_df["text"] = combined_df["text"].astype(str)
combined_df["label"] = combined_df["label"].astype(str).str.strip().str.lower()

le_combined = LabelEncoder()
combined_df["label_id"] = le_combined.fit_transform(combined_df["label"])

X = combined_df["text"]
y = combined_df["label_id"]

# train 70%, val 15%, test 15% stratified
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print("Sizes:", len(X_train), len(X_val), len(X_test))
splits = {}          # reuse/replace previous
encoders = {}
splits["combined"] = {
    "train": (X_train.reset_index(drop=True), y_train.reset_index(drop=True)),
    "val": (X_val.reset_index(drop=True), y_val.reset_index(drop=True)),
    "test": (X_test.reset_index(drop=True), y_test.reset_index(drop=True))
}
encoders["combined"] = le_combined
print("Num classes (combined):", len(le_combined.classes_))

# 3) Tokenizer + dataloader builder
import torch
from transformers import AutoTokenizer
from torch.utils.data import Dataset, DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

def create_dataloaders(dataset_name, max_length=128, batch_size=64):
    X_train, y_train = splits[dataset_name]["train"]
    X_val, y_val = splits[dataset_name]["val"]
    X_test, y_test = splits[dataset_name]["test"]

    def enc(texts):
        return tokenizer(list(texts), padding="max_length", truncation=True, max_length=max_length, return_tensors="pt")

    train_enc = enc(X_train)
    val_enc = enc(X_val)
    test_enc = enc(X_test)

    train_ds = TextDataset(train_enc, y_train.to_numpy())
    val_ds = TextDataset(val_enc, y_val.to_numpy())
    test_ds = TextDataset(test_enc, y_test.to_numpy())

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)

    num_labels = len(np.unique(y_train))
    return train_loader, val_loader, test_loader, num_labels

# quick smoke test
train_loader, val_loader, test_loader, num_labels = create_dataloaders("combined", max_length=128, batch_size=64)
print("Num labels:", num_labels)

# 4) RNN/LSTM/GRU/BiLSTM+RNN/BiLSTM+GRU model definitions
import torch.nn as nn

vocab_size = tokenizer.vocab_size
pad_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else 0

class RNNClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_labels, num_layers=1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=pad_id)
        self.rnn = nn.RNN(embed_dim, hidden_dim, num_layers=num_layers, batch_first=True)
        self.drop = nn.Dropout(0.2)
        self.fc = nn.Linear(hidden_dim, num_labels)
    def forward(self, input_ids, attention_mask=None):
        x = self.embedding(input_ids)
        _, h = self.rnn(x)
        h = h[-1]
        h = self.drop(h)
        return self.fc(h)

class LSTMClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_labels, num_layers=1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=pad_id)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, num_layers=num_layers, batch_first=True)
        self.drop = nn.Dropout(0.2)
        self.fc = nn.Linear(hidden_dim, num_labels)
    def forward(self, input_ids, attention_mask=None):
        x = self.embedding(input_ids)
        _, (h, _) = self.lstm(x)
        h = h[-1]
        h = self.drop(h)
        return self.fc(h)

class GRUClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_labels, num_layers=1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=pad_id)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=num_layers, batch_first=True)
        self.drop = nn.Dropout(0.2)
        self.fc = nn.Linear(hidden_dim, num_labels)
    def forward(self, input_ids, attention_mask=None):
        x = self.embedding(input_ids)
        _, h = self.gru(x)
        h = h[-1]
        h = self.drop(h)
        return self.fc(h)

class BiLSTM_RNN_Classifier(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_bi, hidden_rnn, num_labels):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=pad_id)
        self.bilstm = nn.LSTM(embed_dim, hidden_bi, num_layers=1, batch_first=True, bidirectional=True)
        self.rnn = nn.RNN(2*hidden_bi, hidden_rnn, num_layers=1, batch_first=True)
        self.drop = nn.Dropout(0.2)
        self.fc = nn.Linear(hidden_rnn, num_labels)
    def forward(self, input_ids, attention_mask=None):
        x = self.embedding(input_ids)
        out, _ = self.bilstm(x)
        _, h = self.rnn(out)
        h = h[-1]
        h = self.drop(h)
        return self.fc(h)

class BiLSTM_GRU_Classifier(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_bi, hidden_gru, num_labels):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=pad_id)
        self.bilstm = nn.LSTM(embed_dim, hidden_bi, num_layers=1, batch_first=True, bidirectional=True)
        self.gru = nn.GRU(2*hidden_bi, hidden_gru, num_layers=1, batch_first=True)
        self.drop = nn.Dropout(0.2)
        self.fc = nn.Linear(hidden_gru, num_labels)
    def forward(self, input_ids, attention_mask=None):
        x = self.embedding(input_ids)
        out, _ = self.bilstm(x)
        _, h = self.gru(out)
        h = h[-1]
        h = self.drop(h)
        return self.fc(h)

# 5) Training/eval helpers for RNN-style models and wrapper to run experiments
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, classification_report

def evaluate_rnn(model, loader):
    model.eval()
    all_logits, all_labels = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            labels = batch["labels"].to(device)
            logits = model(input_ids)
            all_logits.append(logits.detach().cpu().numpy())
            all_labels.append(labels.detach().cpu().numpy())
    all_logits = np.concatenate(all_logits, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    preds = np.argmax(all_logits, axis=1)
    acc = accuracy_score(all_labels, preds)
    f1 = f1_score(all_labels, preds, average="macro")
    return acc, f1, preds, all_labels

def train_rnn(model, train_loader, val_loader, epochs=3, lr=1e-3):
    model.to(device)
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    crit = nn.CrossEntropyLoss()
    for ep in range(1, epochs+1):
        model.train()
        tot_loss = 0.0
        for batch in train_loader:
            input_ids = batch["input_ids"].to(device)
            labels = batch["labels"].to(device)
            opt.zero_grad()
            logits = model(input_ids)
            loss = crit(logits, labels)
            loss.backward()
            opt.step()
            tot_loss += loss.item()
        val_acc, val_f1, _, _ = evaluate_rnn(model, val_loader)
        print(f"Epoch {ep}: train_loss={tot_loss/len(train_loader):.4f}, val_acc={val_acc:.4f}, val_f1={val_f1:.4f}")
    return model

def run_rnn_with_metrics(dataset_name, model_type="lstm", epochs=3, batch_size=64, embed_dim=128, hidden_dim=128):
    train_loader, val_loader, test_loader, num_labels = create_dataloaders(dataset_name, max_length=128, batch_size=batch_size)
    vocab_size = tokenizer.vocab_size
    if model_type=="rnn":
        model = RNNClassifier(vocab_size, embed_dim, hidden_dim, num_labels)
    elif model_type=="lstm":
        model = LSTMClassifier(vocab_size, embed_dim, hidden_dim, num_labels)
    elif model_type=="gru":
        model = GRUClassifier(vocab_size, embed_dim, hidden_dim, num_labels)
    elif model_type=="bilstm_rnn":
        model = BiLSTM_RNN_Classifier(vocab_size, embed_dim, hidden_dim, hidden_dim, num_labels)
    elif model_type=="bilstm_gru":
        model = BiLSTM_GRU_Classifier(vocab_size, embed_dim, hidden_dim, hidden_dim, num_labels)
    else:
        raise ValueError("Unknown model type")
    model = train_rnn(model, train_loader, val_loader, epochs=epochs)
    val_acc, val_f1, _, _ = evaluate_rnn(model, val_loader)
    test_acc, test_f1, preds, labels = evaluate_rnn(model, test_loader)
    print(f"[{model_type.upper()}] {dataset_name} -> val_acc={val_acc:.4f}, val_f1={val_f1:.4f}, test_acc={test_acc:.4f}, test_f1={test_f1:.4f}")
    return val_acc, val_f1, test_acc, test_f1

# 6) Transformer (DistilBERT) training & eval (uses create_dataloaders)
from transformers import AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW

def evaluate_transformer(model, loader):
    model.eval()
    all_logits, all_labels = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            all_logits.append(logits.detach().cpu().numpy())
            all_labels.append(labels.detach().cpu().numpy())
    all_logits = np.concatenate(all_logits, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    preds = np.argmax(all_logits, axis=1)
    acc = accuracy_score(all_labels, preds)
    f1 = f1_score(all_labels, preds, average="macro")
    return acc, f1, preds, all_labels

def run_transformer_with_metrics(dataset_name, model_name="distilbert-base-uncased", epochs=2, batch_size=32, max_length=128, lr=2e-5):
    train_loader, val_loader, test_loader, num_labels = create_dataloaders(dataset_name, max_length=max_length, batch_size=batch_size)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels).to(device)
    opt = AdamW(model.parameters(), lr=lr)
    total_steps = len(train_loader)*epochs
    sched = get_linear_schedule_with_warmup(opt, num_warmup_steps=int(0.1*total_steps), num_training_steps=total_steps)
    for ep in range(1, epochs+1):
        model.train()
        tot_loss = 0.0
        for batch in train_loader:
            opt.zero_grad()
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            loss.backward()
            opt.step()
            sched.step()
            tot_loss += loss.item()
        val_acc, val_f1, _, _ = evaluate_transformer(model, val_loader)
        print(f"Epoch {ep}: train_loss={tot_loss/len(train_loader):.4f}, val_acc={val_acc:.4f}, val_f1={val_f1:.4f}")
    val_acc, val_f1, _, _ = evaluate_transformer(model, val_loader)
    test_acc, test_f1, preds, labels = evaluate_transformer(model, test_loader)
    print(f"[TRANSFORMER {model_name}] {dataset_name} -> val_acc={val_acc:.4f}, val_f1={val_f1:.4f}, test_acc={test_acc:.4f}, test_f1={test_f1:.4f}")
    return val_acc, val_f1, test_acc, test_f1

models_to_run = [
    ("lstm", 50),
    ("gru", 50),
    ("bilstm_gru", 50),
    ("bilstm_rnn", 50),
]
exp_results = []

for mtype, epochs in models_to_run:
    print("\n========================")
    print("Model:", mtype)
    print("========================")
    v_acc, v_f1, t_acc, t_f1 = run_rnn_with_metrics("combined", model_type=mtype, epochs=epochs, batch_size=64)
    exp_results.append({"dataset":"combined", "model":mtype.upper(), "val_acc":v_acc, "val_f1":v_f1, "test_acc":t_acc, "test_f1":t_f1})

# Transformer
print("\n========================")
print("Model: DistilBERT")
print("========================")
v_acc, v_f1, t_acc, t_f1 = run_transformer_with_metrics("combined", model_name="distilbert-base-uncased", epochs=10, batch_size=32)
exp_results.append({"dataset":"combined", "model":"DistilBERT", "val_acc":v_acc, "val_f1":v_f1, "test_acc":t_acc, "test_f1":t_f1})

import pandas as pd
results_df = pd.DataFrame(exp_results)
print(results_df)